### ISSUE TITLE
index.html doesn't look right

### ISSUE THREAD

**Issue by Tymewalk** [ilovecode1/scratch-html5#1]
![](http://i.cubeupload.com/1CFMfe.png)
I'm fairly sure it's not supposed to look like this.

**Comment by Tymewalk** [comment]
Just checked, this happens in the other HTML player, too.

**Comment by CosmicWebServices** [comment]
Thanks for the heads up are you sure you compiled the script that may be it.

**Comment by Tymewalk** [comment]
_facepalm_
I didn't know you had to compile scripts. Last time I got the LLK HTML5 player working out-of-the-box.

**Comment by CosmicWebServices** [comment]
I guess they changed it... [Here](https://github.com/ilovecode1/scratch-html5#installation) are the instructions if this problem continues reopen the  issue.
